"""KotobaCore: Japanese semantic understanding engine."""

from kotobacore._version import __version__
from kotobacore.analyzer import Analyzer
from kotobacore.core.ir import (
    AnalysisResult,
    Argument,
    DocumentChunk,
    EmotionExpression,
    EmotionResult,
    Entity,
    Event,
    IntentCandidate,
    IntentResult,
    KotobaError,
    MetaInfo,
    Paragraph,
    Predicate,
    QueryIR,
    RagResult,
    Relation,
    SemanticChunk,
    SemanticToken,
    Sentence,
    SentimentExpression,
    SentimentResult,
    TextInfo,
    Token,
    Topic,
    TopicResult,
)
from kotobacore.errors import (
    BackendInitializeError,
    ConfigError,
    DictionaryLoadError,
    KotobaCoreError,
)

__all__ = [
    "AnalysisResult",
    "Analyzer",
    "Argument",
    "BackendInitializeError",
    "ConfigError",
    "DictionaryLoadError",
    "DocumentChunk",
    "EmotionExpression",
    "EmotionResult",
    "Entity",
    "Event",
    "IntentCandidate",
    "IntentResult",
    "KotobaCoreError",
    "KotobaError",
    "MetaInfo",
    "Paragraph",
    "Predicate",
    "QueryIR",
    "RagResult",
    "Relation",
    "SemanticChunk",
    "SemanticToken",
    "Sentence",
    "SentimentExpression",
    "SentimentResult",
    "TextInfo",
    "Token",
    "Topic",
    "TopicResult",
    "__version__",
]
