"""Generate docs/IR_SCHEMA.md — the Semantic IR field reference (FR-050〜053, §8) from the dataclasses in core/ir.py.

Run after any IR change:  python tools/gen_schema_doc.py
The schema version, the compatibility policy and the component versions are pulled from the code,
so the document cannot drift from what ``AnalysisResult.to_dict()`` actually emits.
"""

from __future__ import annotations

import dataclasses
import sys
import typing
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from kotobacore._version import __version__
from kotobacore.core import ir
from kotobacore.versions import component_versions

# document order: top-level result first, then the nested types as they appear
ORDER = [
    "AnalysisResult", "MetaInfo", "TextInfo", "Token", "SemanticToken", "SemanticChunk", "Entity", "Argument", "Predicate",
    "Relation", "Event", "EmotionExpression", "EmotionResult", "SentimentExpression", "SentimentResult", "IntentCandidate",
    "IntentResult", "Topic", "TopicResult", "Paragraph", "Sentence", "DocumentChunk", "QueryIR", "RagResult", "KotobaError",
]
SINCE = {  # field → version it was added (post-0.3 additions only; everything else is 0.3 = v0.3.0 base)
    "Entity.canonical_id": "0.4 (v0.6.2)", "Entity.aliases": "0.4 (v0.6.2)", "Token.conjugation_type": "0.4 (v0.6.3)",
    "Token.conjugation_form": "0.4 (v0.6.3)", "MetaInfo.components": "0.4 (v0.6.4)", "DocumentChunk.heading_path": "0.3 (v0.5.2)",
    "DocumentChunk.context": "0.3 (v0.5.2)",
}


def type_str(tp) -> str:
    s = str(tp).replace("typing.", "").replace("kotobacore.core.ir.", "")
    return s.replace("<class '", "").replace("'>", "")


def main() -> None:
    v = component_versions(with_dictionaries=False)
    lines = [
        f"# KotobaCore Semantic IR — field reference (schema {ir.SCHEMA_VERSION}, KotobaCore {__version__})", "",
        "Generated by `tools/gen_schema_doc.py` from `kotobacore/core/ir.py`. `AnalysisResult.to_dict()` / `to_json()` emit exactly these fields.", "",
        "## Versioning (要件定義書 §8)", "",
        f"- `meta.schema_version` = **{ir.SCHEMA_VERSION}**. Field additions are backward compatible (minor); removals or type changes are major.",
        "- All spans (`begin` / `end`) are **original-text** character offsets (FR-002 位置写像); `text.offset_map` maps normalized → original.",
        "- Ids: tokens `int` (0-based), entities `e1…`, predicates `p1…`, relations `r1…`, events `ev1…` — unique within one result; coreference shares `canonical_id`, never the id.",
        f"- Component versions stamped in `meta.components`: tokenizer {v['tokenizer']}, dictionary_set {v['dictionary_set']}, modules {v['modules']}.",
        "- Schema history: 0.1 (v0.1 flat result) → 0.2 (v0.4 document hierarchy, entities, query IR) → 0.3 (v0.5 predicates / relations / events / topics, chunk context) → 0.4 (v0.6 coreference, conjugation, components).",
        "",
    ]
    for name in ORDER:
        cls = getattr(ir, name)
        doc = (cls.__doc__ or "").strip().splitlines()[0] if cls.__doc__ else ""
        if doc.startswith(f"{name}("):
            doc = ""  # dataclass auto-repr, not a real docstring
        lines += [f"## {name}", ""]
        if doc:
            lines += [doc, ""]
        lines += ["| field | type | default | since | note |", "|---|---|---|---|---|"]
        hints = typing.get_type_hints(cls)
        for f in dataclasses.fields(cls):
            if f.default is not dataclasses.MISSING:
                default = repr(f.default)
            elif f.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
                default = f.default_factory.__name__ if hasattr(f.default_factory, "__name__") else "factory"
                default = {"list": "[]", "dict": "{}", "<lambda>": "[]"}.get(default, default)
            else:
                default = "required"
            since = SINCE.get(f"{name}.{f.name}", "0.3")
            lines.append(f"| `{f.name}` | `{type_str(hints.get(f.name, f.type))}` | {default} | {since} |  |")
        lines.append("")
    lines += ["## Error codes (`errors[]`, 要件定義書 §9)", "",
              "| code | meaning | recoverable |", "|---|---|---|",
              "| E101 invalid_utf8 | bytes input had invalid UTF-8; replaced with U+FFFD | yes |",
              "| E102 unsupported_character | replacement / surrogate characters removed | yes |",
              "| E201 tokenization_error | lattice failed; character tokens used | yes |",
              "| E301 sentence_boundary_error / E302 entity_error / E303 predicate_error | a Core stage raised; stage skipped | yes |",
              "| E401 module_error / E402 rag_error | a module raised; empty module result | yes |",
              "| E501 invalid_ir / E502 schema_version_mismatch | IR consumers (reserved) | – |",
              "| E601 vocab_version_mismatch / E602 unknown_token | vocab (E601 is an exception, not recorded) | – |",
              "| E700 api_error / E701 unauthorized / E702 rate_limited | HTTP API responses | – |", ""]
    out = ROOT / "docs" / "IR_SCHEMA.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(out, len(lines), "lines")


if __name__ == "__main__":
    main()
